In [3]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

from finvizfinance.quote import finvizfinance

In [ ]:
dat = yf.Ticker("MSFT")

In [ ]:
dat

yfinance.Ticker object <MSFT>

In [4]:
stock = finvizfinance('MSFT')

In [5]:
news_df = stock.ticker_news()
news_df

,Date,Title,Link,Source
0,2025-02-26 13:52:00,Magnificent Seven Stocks: Nvidia Rallies Ahead...,https://finance.yahoo.com/m/4205eaa9-f620-3a0b...,Investor's Business Daily
1,2025-02-26 13:47:00,Nvidias Shaken Aura of Invincibility Is Set fo...,https://finance.yahoo.com/news/nvidia-shaken-a...,Bloomberg
2,2025-02-26 13:08:00,Microsoft Invests in Veeam to Advance AI-Power...,https://finance.yahoo.com/news/microsoft-inves...,GuruFocus.com
3,2025-02-26 12:44:00,Amazon to Launch Generative-AI Alexa+ Next Month,https://finance.yahoo.com/m/beda202b-d9a4-3da7...,The Wall Street Journal
4,2025-02-26 12:34:00,"Salesforce, Microsoft executives spar over AI ...",https://www.youtube.com/watch?v=Qb3cel-14gg,CNBC TV
...,...,...,...,...
95,2025-02-24 04:00:00,Nvidia to report Q4 earnings Wednesday as tari...,https://finance.yahoo.com/news/nvidia-to-repor...,Yahoo Finance
96,2025-02-24 03:34:00,Prediction: 2 AI Stocks Will Be Worth More Tha...,https://finance.yahoo.com/m/71a3a068-5773-3eca...,Motley Fool
97,2025-02-23 22:00:00,Spark New Zealand Ltd (NZTCF) (HY 2025) Earnin...,https://finance.yahoo.com/news/spark-zealand-l...,GuruFocus.com
98,2025-02-23 12:22:00,"At a 6-Month Low, Here's My Top Dow Jones Stoc...",https://finance.yahoo.com/m/f102dbb2-a8cc-3c1e...,Motley Fool
99,2025-02-23 09:55:00,Silicon Valley is going all in on humanoid rob...,https://finance.yahoo.com/news/silicon-valley-...,Yahoo Finance

In [ ]:
CREATE TABLE news_data (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    headline TEXT NOT NULL,
    link TEXT NOT NULL,
    source VARCHAR(100) NOT NULL,
    CONSTRAINT unique_ticker_date_headline UNIQUE (ticker, date, headline)
);

In [ ]:
print(dat.info)
print(dat.calendar)

{'address1': 'One Microsoft Way', 'city': 'Redmond', 'state': 'WA', 'zip': '98052-6399', 'country': 'United States', 'phone': '425 882 8080', 'website': 'https://www.microsoft.com', 'industry': 'Software - Infrastructure', 'industryKey': 'software-infrastructure', 'industryDisp': 'Software - Infrastructure', 'sector': 'Technology', 'sectorKey': 'technology', 'sectorDisp': 'Technology', 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.', 'fullTimeEmployees': 228000, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Satya  Nadella', 'age': 57, 'title': 'Chairman & CEO', 'yearBorn': 1967, 'fiscalYear': 2024, 'totalPay': 7869791, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Bradford L. Smith LCA', 'age': 65, 'title': 'President & Vice Chairman', 'yearBorn': 1959, 'fiscalYear': 2024, 'totalPay': 4755618, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Amy E. Hood', 'age': 52, 'title': 'Executive VP & CFO', 'yearBorn': 1972, 'fiscalYear': 2024, 'totalPay': 4704250, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Christopher David Young', 'age': 52, 'title': 'Executive Officer', 'yearBorn': 1972, 'fiscalYear': 2024, 'totalPay': 2993772, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Carolina  Dybeck Happe', 'age': 52, 'title': 'Executive VP & COO', 'yearBorn': 1972, 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Alice L. Jolla', 'age': 58, 'title': 'Corporate VP & Chief Accounting Officer', 'yearBorn': 1966, 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. James Kevin Scott', 'age': 52, 'title': 'Executive VP of AI & CTO', 'yearBorn': 1972, 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Brett  Iversen', 'title': 'Vice President of Investor Relations', 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Hossein  Nowbar', 'title': 'Chief Legal Officer', 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Frank X. Shaw', 'title': 'Chief Communications Officer', 'fiscalYear': 2024, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 9, 'boardRisk': 5, 'compensationRisk': 3, 'shareHolderRightsRisk': 2, 'overallRisk': 3, 'governanceEpochDate': 1738368000, 'compensationAsOfEpochDate': 1735603200, 'irWebsite': 'http://www.microsoft.com/investor/default.aspx', 'executiveTeam': [], 'maxAge': 86400, 'priceHint': 2, 'previousClose': 397.9, 'open': 398.01, 'dayLow': 394.245, 'dayHigh': 403.6, 'regularMarketPreviousClose': 397.9, 'regularMarketOpen': 398.01, 'regularMarketDayLow': 394.245, 'regularMarketDayHigh': 403.6, 'dividendRate': 3.32, 'dividendYield': 0.83, 'exDividendDate': 1740009600, 'payoutRatio': 0.2482, 'fiveYearAvgDividendYield': 0.86, 'beta': 0.895, 'trailingPE': 32.335213, 'forwardPE': 26.841473, 'volume': 11408729, 'regularMarketVolume': 11409884, 'averageVolume': 21963676, 'averageVolume10days': 23624510, 'averageDailyVolume10Day': 23624510, 'bid': 401.14, 'ask': 401.44, 'bidSize': 1, 'askSize': 1, 'marketCap': 2983107493888, 'fiftyTwoWeekLow': 385.58, 'fiftyTwoWeekHigh': 468.35, 'priceToSalesTrailing12Months': 11.394802, 'fiftyDayAverage': 425.6992, 'twoHundredDayAverage': 426.2149, 'trailingAnnualDividendRate': 3.16, 'trailingAnnualDividendYield': 0.007941694, 'currency': 'USD', 'tradeable': False, 'enterpriseValue': 2989335511040, 'profitMargins': 0.35428002, 'floatShares': 7423723340, 'sharesOutstanding': 7433979904, 'sharesShort': 62492832, 'sharesShortPriorMonth': 62178630, 'sharesShortPreviousMonthDate': 1735603200, 'dateShortInterest': 1738281600, 'sharesPercentSharesOut': 0.0084, 'heldPercentInsiders': 0.00311, 'heldPercentInstitutions': 0.74281, 'shortRatio': 2.76, 'shortPercentOfFloat': 0.0084, 'impliedSharesOutstanding': 7433979904, 'bookValue': 40.712, 'priceToBook': 9.856553, 'lastFiscalYearEnd': 1719705600, 'nextFiscalYearEnd': 1751241600, 'mostRecentQuarter': 1735603200, 'earningsQuarterlyGrowth': 0.102, 'netIncomeToCommon': 92749996032, 'trailingEps': 12.41, 'forwardEps': 14.95, 'lastSplitFactor': '2:1', 'lastSplitDate': 1045526400, 'enterpriseToRevenue': 11.418, 'enterpriseToEbitda': 21.046, '52WeekChange': -0.024085164, 'SandP52WeekChange': 0.17466116, 'lastDividendValue': 0.83, 'lastDividendDate': 1740009600, 'quoteType': 'EQUITY', 'currentPrice': 401.29, 'targetHighPrice': 650.0, 'targetLowPrice': 420.0, 'targetMeanPrice': 508.051, 'targetMedianPrice': 500.0, 'recommendationMean': 1.40351, 'recommendationKey': 'strong_buy', 'numberOfAnalystOpinions': 50, 'totalCash': 71554998272, 'totalCashPerShare': 9.625, 'ebitda': 142041006080, 'totalDebt': 102909001728, 'quickRatio': 1.204, 'currentRatio': 1.351, 'totalRevenue': 261802000384, 'debtToEquity': 33.998, 'revenuePerShare': 35.224, 'returnOnAssets': 0.14649001, 'returnOnEquity': 0.34291, 'grossProfits': 181714993152, 'freeCashflow': 51958124544, 'operatingCashflow': 125582999552, 'earningsGrowth': 0.102, 'revenueGrowth': 0.123, 'grossMargins': 0.69408995, 'ebitdaMargins': 0.54255, 'operatingMargins': 0.45458, 'financialCurrency': 'USD', 'symbol': 'MSFT', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'longName': 'Microsoft Corporation', 'shortName': 'Microsoft Corporation', 'market': 'us_market', 'esgPopulated': False, 'hasPrePostMarketData': True, 'firstTradeDateMilliseconds': 511108200000, 'regularMarketChangePercent': 0.8494609, 'regularMarketPrice': 401.28, 'corporateActions': [], 'regularMarketTime': 1740592510, 'exchange': 'NMS', 'messageBoardId': 'finmb_21835', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'gmtOffSetMilliseconds': -18000000, 'regularMarketChange': 3.380005, 'regularMarketDayRange': '394.245 - 403.6', 'fullExchangeName': 'NasdaqGS', 'averageDailyVolume3Month': 21963676, 'fiftyTwoWeekLowChange': 15.700012, 'fiftyTwoWeekLowChangePercent': 0.04071791, 'fiftyTwoWeekRange': '385.58 - 468.35', 'fiftyTwoWeekHighChange': -67.07001, 'fiftyTwoWeekHighChangePercent': -0.14320488, 'fiftyTwoWeekChangePercent': -2.4085164, 'dividendDate': 1741824000, 'earningsTimestamp': 1738184400, 'earningsTimestampStart': 1745438400, 'earningsTimestampEnd': 1745870400, 'earningsCallTimestampStart': 1738189800, 'earningsCallTimestampEnd': 1738189800, 'isEarningsDateEstimate': True, 'epsTrailingTwelveMonths': 12.41, 'epsForward': 14.95, 'epsCurrentYear': 13.18475, 'priceEpsCurrentYear': 30.435163, 'fiftyDayAverageChange': -24.41919, 'fiftyDayAverageChangePercent': -0.057362545, 'twoHundredDayAverageChange': -24.934906, 'twoHundredDayAverageChangePercent': -0.05850313, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.4 - Strong Buy', 'cryptoTradeable': False, 'marketState': 'REGULAR', 'displayName': 'Microsoft', 'trailingPegRatio': 2.0741}
{'Dividend Date': datetime.date(2025, 3, 13), 'Ex-Dividend Date': datetime.date(2025, 2, 20), 'Earnings Date': [datetime.date(2025, 4, 23), datetime.date(2025, 4, 28)], 'Earnings High': 3.56, 'Earnings Low': 3.16, 'Earnings Average': 3.22615, 'Revenue High': 69897682310, 'Revenue Low': 67140000000, 'Revenue Average': 68534440260}
{'current': 401.28, 'high': 650.0, 'low': 420.0, 'mean': 508.051, 'median': 500.0}

In [ ]:
###SQL TABLES from company_info

CREATE TABLE company_info (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    sector VARCHAR(50),
    industry VARCHAR(50),
    
    market_cap BIGINT,
    enterprise_value BIGINT,
    total_revenue BIGINT,
    ebitda BIGINT,
    net_income BIGINT,
    total_debt BIGINT,
    free_cashflow BIGINT,
    return_on_assets FLOAT,
    return_on_equity FLOAT,

    trailing_pe FLOAT,
    forward_pe FLOAT,
    price_to_sales FLOAT,
    price_to_book FLOAT,

    dividend_rate FLOAT,
    dividend_yield FLOAT,
    payout_ratio FLOAT,

    shares_outstanding BIGINT,
    held_percent_institutions FLOAT,
    held_percent_insiders FLOAT,
    beta FLOAT,
    fifty_two_week_high FLOAT,
    fifty_two_week_low FLOAT,

    earnings_growth FLOAT,
    revenue_growth FLOAT,
    profit_margins FLOAT,
    gross_margins FLOAT,
    operating_margins FLOAT,
    ebitda_margins FLOAT,

    target_high_price FLOAT,
    target_low_price FLOAT,
    target_mean_price FLOAT,
    recommendation_mean FLOAT,
    recommendation_key VARCHAR(20),
    number_of_analyst_opinions INT
);

In [ ]:
print(dat.quarterly_income_stmt)

                                                       2024-12-31  \
Tax Effect Of Unusual Items                          -203220000.0
Tax Rate For Calcs                                           0.18
Normalized EBITDA                                   37915000000.0
Total Unusual Items                                 -1129000000.0
Total Unusual Items Excluding Goodwill              -1129000000.0
Net Income From Continuing Operation Net Minori...  24108000000.0
Reconciled Depreciation                              6827000000.0
Reconciled Cost Of Revenue                          21799000000.0
EBITDA                                              36786000000.0
EBIT                                                29959000000.0
Net Interest Income                                     6000000.0
Interest Expense                                      594000000.0
Interest Income                                       600000000.0
Normalized Income                                   25033780000.0
Net Income From Continuing And Discontinued Ope...  24108000000.0
Total Expenses                                      37979000000.0
Total Operating Income As Reported                  31653000000.0
Diluted Average Shares                               7468000000.0
Basic Average Shares                                 7435000000.0
Diluted EPS                                                  3.23
Basic EPS                                                    3.24
Diluted NI Availto Com Stockholders                 24108000000.0
Net Income Common Stockholders                      24108000000.0
Net Income                                          24108000000.0
Net Income Including Noncontrolling Interests       24108000000.0
Net Income Continuous Operations                    24108000000.0
Tax Provision                                        5257000000.0
Pretax Income                                       29365000000.0
Other Income Expense                                -2294000000.0
Other Non Operating Income Expenses                 -1165000000.0
Special Income Charges                               -867000000.0
Write Off                                             867000000.0
Gain On Sale Of Security                             -262000000.0
Net Non Operating Interest Income Expense               6000000.0
Interest Expense Non Operating                        594000000.0
Interest Income Non Operating                         600000000.0
Operating Income                                    31653000000.0
Operating Expense                                   16180000000.0
Research And Development                             7917000000.0
Selling General And Administration                   8263000000.0
Selling And Marketing Expense                        6440000000.0
General And Administrative Expense                   1823000000.0
Other Gand A                                         1823000000.0
Gross Profit                                        47833000000.0
Cost Of Revenue                                     21799000000.0
Total Revenue                                       69632000000.0
Operating Revenue                                   69632000000.0

                                                       2024-09-30  \
Tax Effect Of Unusual Items                            57190000.0
Tax Rate For Calcs                                           0.19
Normalized EBITDA                                   37933000000.0
Total Unusual Items                                   301000000.0
Total Unusual Items Excluding Goodwill                301000000.0
Net Income From Continuing Operation Net Minori...  24667000000.0
Reconciled Depreciation                              7383000000.0
Reconciled Cost Of Revenue                          20099000000.0
EBITDA                                              38234000000.0
EBIT                                                30851000000.0
Net Interest Income                                    99000000.0
Interest Expense                                      582000000.0
Interest Income                                       681000000.0
Normalized Income                                   24423190000.0
Net Income From Continuing And Discontinued Ope...  24667000000.0
Total Expenses                                      35033000000.0
Total Operating Income As Reported                  30552000000.0
Diluted Average Shares                               7470000000.0
Basic Average Shares                                 7433000000.0
Diluted EPS                                                   3.3
Basic EPS                                                    3.32
Diluted NI Availto Com Stockholders                 24667000000.0
Net Income Common Stockholders                      24667000000.0
Net Income                                          24667000000.0
Net Income Including Noncontrolling Interests       24667000000.0
Net Income Continuous Operations                    24667000000.0
Tax Provision                                        5602000000.0
Pretax Income                                       30269000000.0
Other Income Expense                                 -382000000.0
Other Non Operating Income Expenses                  -683000000.0
Special Income Charges                                 -7000000.0
Write Off                                               7000000.0
Gain On Sale Of Security                              308000000.0
Net Non Operating Interest Income Expense              99000000.0
Interest Expense Non Operating                        582000000.0
Interest Income Non Operating                         681000000.0
Operating Income                                    30552000000.0
Operating Expense                                   14934000000.0
Research And Development                             7544000000.0
Selling General And Administration                   7390000000.0
Selling And Marketing Expense                        5717000000.0
General And Administrative Expense                   1673000000.0
Other Gand A                                         1673000000.0
Gross Profit                                        45486000000.0
Cost Of Revenue                                     20099000000.0
Total Revenue                                       65585000000.0
Operating Revenue                                   65585000000.0

                                                           2024-06-30  \
Tax Effect Of Unusual Items                          -16263853.211009
Tax Rate For Calcs                                           0.191339
Normalized EBITDA                                       34416000000.0
Total Unusual Items                                       -85000000.0
Total Unusual Items Excluding Goodwill                    -85000000.0
Net Income From Continuing Operation Net Minori...      22036000000.0
Reconciled Depreciation                                  6380000000.0
Reconciled Cost Of Revenue                              19684000000.0
EBITDA                                                  34331000000.0
EBIT                                                    27951000000.0
Net Interest Income                                       -63000000.0
Interest Expense                                          701000000.0
Interest Income                                           638000000.0
Normalized Income                                   22104736146.78899
Net Income From Continuing And Discontinued Ope...      22036000000.0
Total Expenses                                          36802000000.0
Total Operating Income As Reported                      27925000000.0
Diluted Average Shares                                   7472000000.0
Basic Average Shares                                     7433000000.0
Diluted EPS                                                      2.95
Basic EPS                                                        2.96
Diluted NI Availto Com Stockholders                     22036000000.0
Net Income Common Stockholders                          22036000000.0
Net Income                                              22036000000.0
Net Income Including Noncontrolling Interests           22036000000.0
Net Income Continuous Operations                        22036000000.0
Tax Provision                                            5214000000.0
Pretax Income                                           27250000000.0
Other Income Expense                                     -612000000.0
Other Non Operating Income Expenses                      -527000000.0
Special Income Charges                                    -22000000.0
Write Off                                                  22000000.0
Gain On Sale Of Security                                  -63000000.0
Net Non Operating Interest Income Expense                 -63000000.0
Interest Expense Non Operating                            701000000.0
Interest Income Non Operating                             638000000.0
Operating Income                                        27925000000.0
Operating Expense                                       17118000000.0
Research And Development                                 8056000000.0
Selling General And Administration                       9062000000.0
Selling And Marketing Expense                            6816000000.0
General And Administrative Expense                       2246000000.0
Other Gand A                                             2246000000.0
Gross Profit                                            45043000000.0
Cost Of Revenue                                         19684000000.0
Total Revenue                                           64727000000.0
Operating Revenue                                       64727000000.0

                                                       2024-03-31  \
Tax Effect Of Unusual Items                           -33660000.0
Tax Rate For Calcs                                           0.18
Normalized EBITDA                                   33741000000.0
Total Unusual Items                                  -187000000.0
Total Unusual Items Excluding Goodwill               -187000000.0
Net Income From Continuing Operation Net Minori...  21939000000.0
Reconciled Depreciation                              6027000000.0
Reconciled Cost Of Revenue                          18505000000.0
EBITDA                                              33554000000.0
EBIT                                                27527000000.0
Net Interest Income                                  -181000000.0
Interest Expense                                      800000000.0
Interest Income                                       619000000.0
Normalized Income                                   22092340000.0
Net Income From Continuing And Discontinued Ope...  21939000000.0
Total Expenses                                      34277000000.0
Total Operating Income As Reported                  27581000000.0
Diluted Average Shares                               7472000000.0
Basic Average Shares                                 7431000000.0
Diluted EPS                                                  2.94
Basic EPS                                                    2.95
Diluted NI Availto Com Stockholders                 21939000000.0
Net Income Common Stockholders                      21939000000.0
Net Income                                          21939000000.0
Net Income Including Noncontrolling Interests       21939000000.0
Net Income Continuous Operations                    21939000000.0
Tax Provision                                        4788000000.0
Pretax Income                                       26727000000.0
Other Income Expense                                 -673000000.0
Other Non Operating Income Expenses                  -486000000.0
Special Income Charges                                -17000000.0
Write Off                                              17000000.0
Gain On Sale Of Security                             -170000000.0
Net Non Operating Interest Income Expense            -181000000.0
Interest Expense Non Operating                        800000000.0
Interest Income Non Operating                         619000000.0
Operating Income                                    27581000000.0
Operating Expense                                   15772000000.0
Research And Development                             7653000000.0
Selling General And Administration                   8119000000.0
Selling And Marketing Expense                        6207000000.0
General And Administrative Expense                   1912000000.0
Other Gand A                                         1912000000.0
Gross Profit                                        43353000000.0
Cost Of Revenue                                     18505000000.0
Total Revenue                                       61858000000.0
Operating Revenue                                   61858000000.0

                                                       2023-12-31
Tax Effect Of Unusual Items                           -29160000.0
Tax Rate For Calcs                                           0.18
Normalized EBITDA                                   33556000000.0
Total Unusual Items                                  -162000000.0
Total Unusual Items Excluding Goodwill               -162000000.0
Net Income From Continuing Operation Net Minori...  21870000000.0
Reconciled Depreciation                              5959000000.0
Reconciled Cost Of Revenue                          19623000000.0
EBITDA                                              33394000000.0
EBIT                                                27435000000.0
Net Interest Income                                  -175000000.0
Interest Expense                                      909000000.0
Interest Income                                       734000000.0
Normalized Income                                   22002840000.0
Net Income From Continuing And Discontinued Ope...  21870000000.0
Total Expenses                                      34988000000.0
Total Operating Income As Reported                  27032000000.0
Diluted Average Shares                               7468000000.0
Basic Average Shares                                 7432000000.0
Diluted EPS                                                  2.93
Basic EPS                                                    2.94
Diluted NI Availto Com Stockholders                 21870000000.0
Net Income Common Stockholders                      21870000000.0
Net Income                                          21870000000.0
Net Income Including Noncontrolling Interests       21870000000.0
Net Income Continuous Operations                    21870000000.0
Tax Provision                                        4656000000.0
Pretax Income                                       26526000000.0
Other Income Expense                                 -331000000.0
Other Non Operating Income Expenses                  -169000000.0
Special Income Charges                               -161000000.0
Write Off                                             161000000.0
Gain On Sale Of Security                               -1000000.0
Net Non Operating Interest Income Expense            -175000000.0
Interest Expense Non Operating                        909000000.0
Interest Income Non Operating                         734000000.0
Operating Income                                    27032000000.0
Operating Expense                                   15365000000.0
Research And Development                             7142000000.0
Selling General And Administration                   8223000000.0
Selling And Marketing Expense                        6246000000.0
General And Administrative Expense                   1977000000.0
Other Gand A                                         1977000000.0
Gross Profit                                        42397000000.0
Cost Of Revenue                                     19623000000.0
Total Revenue                                       62020000000.0
Operating Revenue                                   62020000000.0

In [19]:
dat.quarterly_financials.index

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Total Operating Income As Reported',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Income Expense', 'Other Non Operating Income Expenses',
       'Special Income Charges', 'Write Off', 'Gain On Sale Of Security',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Research And Development',
       'Selling General And Administration', 'Selling And Marketing Expense',
       'General And Administrative Expense', 'Other Gand A', 'Gross Profit',
       'Cost Of Revenue', 'Total Revenue', 'Operating Revenue'],
      dtype='object')

In [12]:
dat.quarterly_financials

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31
Tax Effect Of Unusual Items,-203220000.0,57190000.0,-16263853.211009,-33660000.0,-29160000.0
Tax Rate For Calcs,0.18,0.19,0.191339,0.18,0.18
Normalized EBITDA,37915000000.0,37933000000.0,34416000000.0,33741000000.0,33556000000.0
Total Unusual Items,-1129000000.0,301000000.0,-85000000.0,-187000000.0,-162000000.0
Total Unusual Items Excluding Goodwill,-1129000000.0,301000000.0,-85000000.0,-187000000.0,-162000000.0
Net Income From Continuing Operation Net Minority Interest,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Reconciled Depreciation,6827000000.0,7383000000.0,6380000000.0,6027000000.0,5959000000.0
Reconciled Cost Of Revenue,21799000000.0,20099000000.0,19684000000.0,18505000000.0,19623000000.0
EBITDA,36786000000.0,38234000000.0,34331000000.0,33554000000.0,33394000000.0
EBIT,29959000000.0,30851000000.0,27951000000.0,27527000000.0,27435000000.0
Net Interest Income,6000000.0,99000000.0,-63000000.0,-181000000.0,-175000000.0
Interest Expense,594000000.0,582000000.0,701000000.0,800000000.0,909000000.0
Interest Income,600000000.0,681000000.0,638000000.0,619000000.0,734000000.0
Normalized Income,25033780000.0,24423190000.0,22104736146.78899,22092340000.0,22002840000.0
Net Income From Continuing And Discontinued Operation,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Total Expenses,37979000000.0,35033000000.0,36802000000.0,34277000000.0,34988000000.0
Total Operating Income As Reported,31653000000.0,30552000000.0,27925000000.0,27581000000.0,27032000000.0
Diluted Average Shares,7468000000.0,7470000000.0,7472000000.0,7472000000.0,7468000000.0
Basic Average Shares,7435000000.0,7433000000.0,7433000000.0,7431000000.0,7432000000.0
Diluted EPS,3.23,3.3,2.95,2.94,2.93
Basic EPS,3.24,3.32,2.96,2.95,2.94
Diluted NI Availto Com Stockholders,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Net Income Common Stockholders,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Net Income,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Net Income Including Noncontrolling Interests,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Net Income Continuous Operations,24108000000.0,24667000000.0,22036000000.0,21939000000.0,21870000000.0
Tax Provision,5257000000.0,5602000000.0,5214000000.0,4788000000.0,4656000000.0
Pretax Income,29365000000.0,30269000000.0,27250000000.0,26727000000.0,26526000000.0
Other Income Expense,-2294000000.0,-382000000.0,-612000000.0,-673000000.0,-331000000.0
Other Non Operating Income Expenses,-1165000000.0,-683000000.0,-527000000.0,-486000000.0,-169000000.0
Special Income Charges,-867000000.0,-7000000.0,-22000000.0,-17000000.0,-161000000.0
Write Off,867000000.0,7000000.0,22000000.0,17000000.0,161000000.0
Gain On Sale Of Security,-262000000.0,308000000.0,-63000000.0,-170000000.0,-1000000.0
Net Non Operating Interest Income Expense,6000000.0,99000000.0,-63000000.0,-181000000.0,-175000000.0
Interest Expense Non Operating,594000000.0,582000000.0,701000000.0,800000000.0,909000000.0
Interest Income Non Operating,600000000.0,681000000.0,638000000.0,619000000.0,734000000.0
Operating Income,31653000000.0,30552000000.0,27925000000.0,27581000000.0,27032000000.0
Operating Expense,16180000000.0,14934000000.0,17118000000.0,15772000000.0,15365000000.0
Research And Development,7917000000.0,7544000000.0,8056000000.0,7653000000.0,7142000000.0
Selling General And Administration,8263000000.0,7390000000.0,9062000000.0,8119000000.0,8223000000.0
Selling And Marketing Expense,6440000000.0,5717000000.0,6816000000.0,6207000000.0,6246000000.0
General And Administrative Expense,1823000000.0,1673000000.0,2246000000.0,1912000000.0,1977000000.0
Other Gand A,1823000000.0,1673000000.0,2246000000.0,1912000000.0,1977000000.0
Gross Profit,47833000000.0,45486000000.0,45043000000.0,43353000000.0,42397000000.0
Cost Of Revenue,21799000000.0,20099000000.0,19684000000.0,18505000000.0,19623000000.0
Total Revenue,69632000000.0,65585000000.0,64727000000.0,61858000000.0,62020000000.0
Operating Revenue,69632000000.0,65585000000.0,64727000000.0,61858000000.0,62020000000.0

In [ ]:
## SQL TABLES QUARTERLY BALANCE
CREATE TABLE quarterly_financials (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,  
    date_reported DATE NOT NULL, 
    tax_effect_of_unusual_items FLOAT,
    tax_rate_for_calcs FLOAT,
    normalized_ebitda FLOAT,
    total_unusual_items FLOAT,
    total_unusual_items_excl_goodwill FLOAT,
    net_income_cont_operation FLOAT,
    reconciled_depreciation FLOAT,
    reconciled_cost_of_revenue FLOAT,
    ebitda FLOAT,
    ebit FLOAT,
    net_interest_income FLOAT,
    interest_expense FLOAT,
    interest_income FLOAT,
    normalized_income FLOAT,
    net_income_cont_discont_operation FLOAT,
    total_expenses FLOAT,
    total_operating_income FLOAT,
    diluted_avg_shares FLOAT,
    basic_avg_shares FLOAT,
    diluted_eps FLOAT,
    basic_eps FLOAT,
    diluted_ni_availto_com_stockholders FLOAT,
    net_income_common_stockholders FLOAT,
    net_income FLOAT,
    net_income_incl_noncontrolling_interests FLOAT,
    net_income_continuous_operations FLOAT,
    tax_provision FLOAT,
    pretax_income FLOAT,
    other_income_expense FLOAT,
    other_non_operating_income_expenses FLOAT,
    special_income_charges FLOAT,
    write_off FLOAT,
    gain_on_sale_of_security FLOAT,
    net_non_operating_interest_income_expense FLOAT,
    interest_expense_non_operating FLOAT,
    interest_income_non_operating FLOAT,
    operating_income FLOAT,
    operating_expense FLOAT,
    research_and_development FLOAT,
    selling_general_and_admin FLOAT,
    selling_and_marketing_expense FLOAT,
    general_and_admin_expense FLOAT,
    other_gand_a FLOAT,
    gross_profit FLOAT,
    cost_of_revenue FLOAT,
    total_revenue FLOAT,
    operating_revenue FLOAT,
    CONSTRAINT unique_ticker_date UNIQUE (ticker, date_reported)
);

In [7]:
print(dat.history(period='1mo'))

                                 Open        High         Low       Close  \
Date
2025-01-27 00:00:00-05:00  423.161523  434.329133  422.652534  433.690399
2025-01-28 00:00:00-05:00  433.730323  447.482746  430.516765  446.305115
2025-01-29 00:00:00-05:00  445.796115  445.985737  439.518694  441.444824
2025-01-30 00:00:00-05:00  417.931980  422.013792  412.333221  414.159546
2025-01-31 00:00:00-05:00  418.141600  419.848170  414.079737  414.229431
2025-02-03 00:00:00-05:00  410.776349  414.578723  407.842230  410.097717
2025-02-04 00:00:00-05:00  411.864167  413.091716  408.920058  411.544800
2025-02-05 00:00:00-05:00  411.524861  413.001880  409.578751  412.462982
2025-02-06 00:00:00-05:00  413.171550  417.363157  413.171550  414.987915
2025-02-07 00:00:00-05:00  415.646597  417.812238  407.283362  408.930054
2025-02-10 00:00:00-05:00  412.882120  414.628618  410.097725  411.395111
2025-02-11 00:00:00-05:00  408.820283  411.664555  408.480936  410.616669
2025-02-12 00:00:00-05:00  406.395111  409.928036  403.560798  408.221466
2025-02-13 00:00:00-05:00  406.185551  410.177546  405.546817  409.718475
2025-02-14 00:00:00-05:00  406.973967  408.091721  405.067786  407.612671
2025-02-18 00:00:00-05:00  407.183549  409.778352  405.686551  408.820282
2025-02-19 00:00:00-05:00  407.063806  414.658563  406.834255  413.940002
2025-02-20 00:00:00-05:00  415.290009  419.309998  412.540009  416.130005
2025-02-21 00:00:00-05:00  417.339996  418.049988  407.890015  408.209991
2025-02-24 00:00:00-05:00  408.510010  409.369995  399.320007  404.000000
2025-02-25 00:00:00-05:00  401.100006  401.920013  396.700012  397.899994
2025-02-26 00:00:00-05:00  398.010010  403.600006  394.244995  401.399994

                             Volume  Dividends  Stock Splits
Date
2025-01-27 00:00:00-05:00  35647800       0.00           0.0
2025-01-28 00:00:00-05:00  23491700       0.00           0.0
2025-01-29 00:00:00-05:00  23581400       0.00           0.0
2025-01-30 00:00:00-05:00  54586300       0.00           0.0
2025-01-31 00:00:00-05:00  34223400       0.00           0.0
2025-02-03 00:00:00-05:00  25679100       0.00           0.0
2025-02-04 00:00:00-05:00  20532100       0.00           0.0
2025-02-05 00:00:00-05:00  16316700       0.00           0.0
2025-02-06 00:00:00-05:00  16309800       0.00           0.0
2025-02-07 00:00:00-05:00  22886800       0.00           0.0
2025-02-10 00:00:00-05:00  20817900       0.00           0.0
2025-02-11 00:00:00-05:00  18140600       0.00           0.0
2025-02-12 00:00:00-05:00  19121700       0.00           0.0
2025-02-13 00:00:00-05:00  23891700       0.00           0.0
2025-02-14 00:00:00-05:00  22758500       0.00           0.0
2025-02-18 00:00:00-05:00  21423100       0.00           0.0
2025-02-19 00:00:00-05:00  24114200       0.00           0.0
2025-02-20 00:00:00-05:00  23508700       0.83           0.0
2025-02-21 00:00:00-05:00  27524800       0.00           0.0
2025-02-24 00:00:00-05:00  26443700       0.00           0.0
2025-02-25 00:00:00-05:00  29318100       0.00           0.0
2025-02-26 00:00:00-05:00  11418216       0.00           0.0

In [ ]:
CREATE TABLE historical_prices ( 
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    open_price DECIMAL(10,2) NOT NULL,
    high_price DECIMAL(10,2) NOT NULL, 
    low_price DECIMAL(10,2) NOT NULL, 
    close_price DECIMAL(10,2) NOT NULL,
    adj_close_price DECIMAL(10,2) NOT NULL,
    volume BIGINT NOT NULL
);"

In [8]:
print(dat.option_chain(dat.options[0]).calls)

         contractSymbol             lastTradeDate  strike  lastPrice     bid  \
0   MSFT250228C00240000 2025-02-12 15:08:15+00:00   240.0     167.72  160.95
1   MSFT250228C00250000 2025-02-21 20:17:26+00:00   250.0     159.59  150.95
2   MSFT250228C00260000 2025-02-19 16:17:02+00:00   260.0     151.12  140.95
3   MSFT250228C00270000 2025-02-06 16:30:58+00:00   270.0     147.30  131.20
4   MSFT250228C00300000 2025-01-31 19:55:07+00:00   300.0     117.17  101.20
..                  ...                       ...     ...        ...     ...
64  MSFT250228C00525000 2025-01-30 17:45:47+00:00   525.0       0.07    0.00
65  MSFT250228C00530000 2025-02-14 15:25:23+00:00   530.0       0.01    0.00
66  MSFT250228C00540000 2025-02-07 19:32:08+00:00   540.0       0.02    0.00
67  MSFT250228C00550000 2025-02-07 18:58:41+00:00   550.0       0.01    0.00
68  MSFT250228C00560000 2025-02-25 17:40:42+00:00   560.0       0.01    0.00

       ask  change  percentChange  volume  openInterest  impliedVolatility  \
0   164.75     0.0            0.0     NaN             0           3.244143
1   154.75     0.0            0.0     3.0             3           3.021487
2   144.75     0.0            0.0     NaN             0           2.806644
3   135.05     0.0            0.0     1.0             0           2.689456
4   105.10     0.0            0.0     7.0             7           2.090825
..     ...     ...            ...     ...           ...                ...
64    0.01     0.0            0.0    20.0            34           0.906251
65    0.01     0.0            0.0     3.0             6           0.937501
66    0.01     0.0            0.0     5.0            21           0.984375
67    0.01     0.0            0.0     3.0            45           1.031255
68    0.01     0.0            0.0     2.0           184           1.093755

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
..         ...          ...      ...
64       False      REGULAR      USD
65       False      REGULAR      USD
66       False      REGULAR      USD
67       False      REGULAR      USD
68       False      REGULAR      USD

[69 rows x 14 columns]

In [ ]:
# SQL TABLES options

CREATE TABLE options_data (
    id SERIAL PRIMARY KEY,
    contract_symbol VARCHAR(50) NOT NULL,  -
    ticker VARCHAR(10) NOT NULL,  
    last_trade_date TIMESTAMP NOT NULL,  
    strike FLOAT NOT NULL,  
    last_price FLOAT NOT NULL,  
    bid FLOAT,  
    ask FLOAT,  
    change FLOAT,  -- Cambio en el precio
    percent_change FLOAT,  
    volume INT,  
    open_interest INT,  -- NÃºmero de contratos abiertos
    implied_volatility FLOAT,  -- Volatilidad implÃ­cita
    in_the_money BOOLEAN NOT NULL,  
    contract_size VARCHAR(10) NOT NULL,  
    currency VARCHAR(3) NOT NULL,  
    CONSTRAINT unique_contract UNIQUE (contract_symbol)
);

In [20]:
dat.option_chain(dat.options[0]).calls.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='object')

In [11]:
dat.balance_sheet

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Share Issued,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Net Debt,33315000000.0,12533000000.0,35850000000.0,43922000000.0
Total Debt,67127000000.0,59965000000.0,61270000000.0,67775000000.0
Tangible Book Value,121660000000.0,128971000000.0,87720000000.0,84477000000.0
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,75531000000.0,111256000000.0,104749000000.0,130256000000.0
Other Short Term Investments,57216000000.0,76552000000.0,90818000000.0,116032000000.0
Cash And Cash Equivalents,18315000000.0,34704000000.0,13931000000.0,14224000000.0
Cash Equivalents,6744000000.0,26226000000.0,5673000000.0,6952000000.0
Cash Financial,11571000000.0,8478000000.0,8258000000.0,7272000000.0

In [18]:
dat.balance_sheet.index

Index(['Ordinary Shares Number', 'Share Issued', 'Net Debt', 'Total Debt',
       'Tangible Book Value', 'Invested Capital', 'Working Capital',
       'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Retained Earnings', 'Capital Stock',
       'Common Stock', 'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities', 'Tradeand Other Payables Non Current',
       'Non Current Deferred Liabilities', 'Non Current Deferred Revenue',
       'Non Current Deferred Taxes Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Current Liabilities', 'Other Current Liabilities',
       'Current Deferred Liabilities', 'Current Deferred Revenue',
       'Current Debt And Capital Lease Obligation', 'Current Debt',
       'Other Current Borrowings', 'Commercial Paper',
       'Pensionand Other Post Retirement Benefit Plans Current',
       'Payables And Accrued Expenses', 'Payables', 'Total Tax Payable',
       'Income Tax Payable', 'Accounts Payable', 'Total Assets',
       'Total Non Current Assets', 'Other Non Current Assets',
       'Financial Assets', 'Investments And Advances',
       'Investmentin Financial Assets', 'Available For Sale Securities',
       'Long Term Equity Investment', 'Goodwill And Other Intangible Assets',
       'Other Intangible Assets', 'Goodwill', 'Net PPE',
       'Accumulated Depreciation', 'Gross PPE', 'Leases', 'Other Properties',
       'Machinery Furniture Equipment', 'Buildings And Improvements',
       'Land And Improvements', 'Properties', 'Current Assets',
       'Other Current Assets', 'Hedging Assets Current', 'Inventory',
       'Finished Goods', 'Work In Process', 'Raw Materials', 'Receivables',
       'Accounts Receivable', 'Allowance For Doubtful Accounts Receivable',
       'Gross Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

# Recomendaciones

In [16]:
print(dat.analyst_price_targets)

{'current': 401.28, 'high': 650.0, 'low': 420.0, 'mean': 508.051, 'median': 500.0}

In [15]:
dat.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         13   39     5     0           0
1    -1m         13   40     5     0           0
2    -2m         14   38     5     0           0
3    -3m         14   38     5     0           0

In [ ]:
##SQL TABLES

CREATE TABLE Analyst_Recommendations (
    id serial primary key,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    latest_stock_price FLOAT NOT NULL,
    high_target FLOAT NOT NULL,
    low_target FLOAT NOT NULL,
    mean_target FLOAT NOT NULL,
    median_target FLOAT NOT NULL,
    CONSTRAINT unique_ticker_date_target UNIQUE (ticker, date)
)

CREATE TABLE Analyst_Recommendations_Period(
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    strong_buy INT NOT NULL,
    buy INT NOT NULL,
    hold INT NOT NULL,
    sell INT NOT NULL,
    strong_sell INT NOT NULL,
    CONSTRAINT unique_ticker_date_recommendations UNIQUE (ticker, date),
    CONSTRAINT fk_analyst_recommendations FOREIGN KEY (ticker, date)
        REFERENCES Analyst_Recommendations (ticker, date) ON DELETE CASCADE
)

# Institutional shareholders

In [14]:
dat.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2024-12-31,Vanguard Group Inc,0.0920,684071705,274045955719,0.0155
1,2024-12-31,Blackrock Inc.,0.0775,576226642,230842146610,0.0263
2,2024-12-31,State Street Corporation,0.0397,295109622,118223861346,0.0194
3,2024-12-31,"FMR, LLC",0.0266,197512226,79125369964,-0.0667
4,2024-12-31,"Geode Capital Management, LLC",0.0226,168128024,67353765231,0.0188
5,2024-12-31,JP Morgan Chase & Company,0.0182,134943661,54059778056,-0.0211
6,2024-12-31,Price (T.Rowe) Associates Inc,0.0182,135151848,54143179847,-0.0037
7,2024-12-31,Morgan Stanley,0.0169,125501255,50277055927,0.0117
8,2024-12-31,Norges Bank Investment Management,0.0142,105202984,42145365879,0.0838
9,2024-12-31,Northern Trust Corporation,0.0113,83787746,33566207697,0.1607

In [ ]:
##SQL TABLES

CREATE TABLE institutional_shareholders (
    id serial primary key,
    ticker VARCHAR(10) NOT NULL,
    date_reported DATE NOT NULL,
    holder VARCHAR(40) NOT NULL,
    pct_held FLOAT NOT NULL,
    shares BIGINT NOT NULL,
    value BIGINT NOT NULL,
    pct_change FLOAT NOT NULL,
    CONSTRAINT unique_institutional_holding UNIQUE (ticker, holder, date_reported)
);

Fondos

In [1]:
import yfinance as yf

In [2]:
spy = yf.Ticker('SPY').funds_data
spy.description

'The trust seeks to achieve its investment objective by holding a portfolio of the common stocks that are included in the index, with the weight of each stock in the portfolio substantially corresponding to the weight of such stock in the index.'

In [3]:
spy.top_holdings

                                  Name  Holding Percent
Symbol
AAPL                         Apple Inc         0.069699
MSFT                    Microsoft Corp         0.060293
NVDA                       NVIDIA Corp         0.057546
AMZN                    Amazon.com Inc         0.043459
META        Meta Platforms Inc Class A         0.029354
GOOGL             Alphabet Inc Class A         0.023291
TSLA                         Tesla Inc         0.022077
AVGO                      Broadcom Inc         0.020192
GOOG              Alphabet Inc Class C         0.019118
BRK-B   Berkshire Hathaway Inc Class B         0.016784

In [ ]:
##SQL TABLES FUNDS

CREATE TABLE funds_holdings (
    id serial primary key,
    fund_ticker VARCHAR(10) NOT NULL,
    date_reported DATE NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    holding_percent FLOAT NOT NULL,
    CONSTRAINT unique_fund_symbol UNIQUE (fund_ticker, symbol, date_reported)
);

In [4]:
df = spy.top_holdings
df.columns

Index(['Name', 'Holding Percent'], dtype='object')

In [5]:
df.index

Index(['AAPL', 'MSFT', 'NVDA', 'AMZN', 'META', 'GOOGL', 'TSLA', 'AVGO', 'GOOG',
       'BRK-B'],
      dtype='object', name='Symbol')